name: Reusable Workflow
on:
  workflow_call:
    inputs:
      some-input:
        description: Required input to run this workflow
        required: true # optionally can be false
        default: Default Value
        type: string # boolean, ... others
    outputs:
      my-deploy-result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  reusable-deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Print Input Passed in
        run: |
          echo "${{ inputs.some-input }}"
      - name: Output information
        run: echo "Deploying & uploading"
      - name: Set result output
        run: echo "my-deploy-result=echo 'something-funny'" >> $GITHUB_OUTPUT
